name: Develop Branch Deploy with Vercel

on:
  push:
    branches: [develop]

jobs:
  ci:
    uses: Central-MakeUs/AZIT_Front/.github/workflows/ci.yml@develop
    secrets: inherit

  build:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare project structure
        run: |
          set -e
          mkdir -p output
          rsync -av --exclude='.github' ./ output/

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: 'output'
          destination-github-username: seseoju
          destination-repository-name: AZIT_Front
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: develop
